apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: data-server
  labels:
    app: data-server
spec:
  template:
    metadata:
      name: data-server
      labels:
        app: data-server
    spec:
      containers:
      - name: data-server
        image: test.caicloudprivatetest.com/library/data:v0.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: data-server
spec:
  ports:
  - port: 8082
    targetPort: 8082
  selector:
    app: data-server
