apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: eureka-server
  labels:
    app: eureka-server
spec:
  template:
    metadata:
      name: eureka-server
      labels:
        app: eureka-server
    spec:
      containers:
      - name: eureka-server
        image: test.caicloudprivatetest.com/library/eureka:v0.0.1
        ports:
        - containerPort: 8761
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-server
spec:
  type: NodePort
  ports:
  - port: 8761
    targetPort: 8761
    nodePort: 30062
  selector:
    app: eureka-server
