apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis-server
  labels:
    app: redis-server
spec:
  template:
    metadata:
      name: redis-server
      labels:
        app: redis-server
    spec:
      containers:
      - name: redis-server
        image: test.caicloudprivatetest.com/library/redis:v0.0.1
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-server
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis-server
